language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/registration_test


node_js:  
  - "12"

before_script:
  - psql -c 'create database registration_test;' -U postgres
  - psql -U postgres -d registration_test -a -f table.sql

services:
  - postgresql